# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1197, 695)
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_master = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_master.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_master.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_master.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_master.setMovable(True)
        self.tabWidget_master.setTabBarAutoHide(True)
        self.tabWidget_master.setObjectName("tabWidget_master")
        self.tab_instance = QtWidgets.QWidget()
        self.tab_instance.setObjectName("tab_instance")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_instance)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tabWidget_instance = QtWidgets.QTabWidget(self.tab_instance)
        self.tabWidget_instance.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_instance.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_instance.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget_instance.setUsesScrollButtons(True)
        self.tabWidget_instance.setDocumentMode(True)
        self.tabWidget_instance.setTabsClosable(False)
        self.tabWidget_instance.setMovable(True)
        self.tabWidget_instance.setTabBarAutoHide(True)
        self.tabWidget_instance.setObjectName("tabWidget_instance")
        self.tab_i_graphics = QtWidgets.QWidget()
        self.tab_i_graphics.setObjectName("tab_i_graphics")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_i_graphics)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_i_graphics)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_instance = QtWidgets.QVBoxLayout()
        self.verticalLayout_instance.setObjectName("verticalLayout_instance")
        self.horizontalLayout.addLayout(self.verticalLayout_instance)
        self.horizontalLayout_14.addWidget(self.groupBox_2)
        self.line_3 = QtWidgets.QFrame(self.tab_i_graphics)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_14.addWidget(self.line_3)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_i_graphics)
        self.groupBox_8.setMinimumSize(QtCore.QSize(253, 330))
        self.groupBox_8.setMaximumSize(QtCore.QSize(253, 330))
        self.groupBox_8.setObjectName("groupBox_8")
        self.lineEdit_lp = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_lp.setGeometry(QtCore.QRect(130, 60, 101, 20))
        self.lineEdit_lp.setStyleSheet("background:rgb(225, 225, 225)")
        self.lineEdit_lp.setReadOnly(True)
        self.lineEdit_lp.setObjectName("lineEdit_lp")
        self.lineEdit_greedy = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_greedy.setGeometry(QtCore.QRect(130, 90, 101, 20))
        self.lineEdit_greedy.setStyleSheet("background:rgb(225, 225, 225)")
        self.lineEdit_greedy.setReadOnly(True)
        self.lineEdit_greedy.setObjectName("lineEdit_greedy")
        self.lineEdit_descent = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_descent.setGeometry(QtCore.QRect(130, 120, 101, 20))
        self.lineEdit_descent.setStyleSheet("background:rgb(225, 225, 225)")
        self.lineEdit_descent.setReadOnly(True)
        self.lineEdit_descent.setObjectName("lineEdit_descent")
        self.lineEdit_tabu = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_tabu.setGeometry(QtCore.QRect(130, 150, 101, 20))
        self.lineEdit_tabu.setStyleSheet("background:rgb(225, 225, 225)")
        self.lineEdit_tabu.setReadOnly(True)
        self.lineEdit_tabu.setObjectName("lineEdit_tabu")
        self.lineEdit_tabudiv = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_tabudiv.setGeometry(QtCore.QRect(130, 180, 101, 20))
        self.lineEdit_tabudiv.setStyleSheet("background:rgb(225, 225, 225)")
        self.lineEdit_tabudiv.setReadOnly(True)
        self.lineEdit_tabudiv.setObjectName("lineEdit_tabudiv")
        self.lineEdit_amamen = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_amamen.setGeometry(QtCore.QRect(130, 210, 101, 20))
        self.lineEdit_amamen.setStyleSheet("background:rgb(225, 225, 225)")
        self.lineEdit_amamen.setReadOnly(True)
        self.lineEdit_amamen.setObjectName("lineEdit_amamen")
        self.lineEdit_amasp = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_amasp.setGeometry(QtCore.QRect(130, 240, 101, 20))
        self.lineEdit_amasp.setStyleSheet("background:rgb(225, 225, 225)")
        self.lineEdit_amasp.setReadOnly(True)
        self.lineEdit_amasp.setObjectName("lineEdit_amasp")
        self.lineEdit_ig = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_ig.setGeometry(QtCore.QRect(130, 270, 101, 20))
        self.lineEdit_ig.setStyleSheet("background:rgb(225, 225, 225)")
        self.lineEdit_ig.setReadOnly(True)
        self.lineEdit_ig.setObjectName("lineEdit_ig")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 221, 21))
        font = QtGui.QFont()
        font.setKerning(True)
        self.textBrowser.setFont(font)
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setStyleSheet("background:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.989, stop:0.0738636 rgba(255, 255, 255, 0))")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setLineWidth(0)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 300, 211, 20))
        self.textBrowser_2.setAutoFillBackground(True)
        self.textBrowser_2.setStyleSheet("background:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.989, stop:0.0738636 rgba(255, 255, 255, 0))")
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_2.setLineWidth(0)
        self.textBrowser_2.setTabChangesFocus(False)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_3.setGeometry(QtCore.QRect(80, 240, 41, 21))
        self.textBrowser_3.setAutoFillBackground(True)
        self.textBrowser_3.setStyleSheet("background:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.989, stop:0.0738636 rgba(255, 255, 255, 0))")
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_3.setLineWidth(0)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_4.setGeometry(QtCore.QRect(70, 210, 51, 21))
        self.textBrowser_4.setAutoFillBackground(True)
        self.textBrowser_4.setStyleSheet("background:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.989, stop:0.0738636 rgba(255, 255, 255, 0))")
        self.textBrowser_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_4.setLineWidth(0)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_5.setGeometry(QtCore.QRect(70, 180, 51, 21))
        self.textBrowser_5.setAutoFillBackground(True)
        self.textBrowser_5.setStyleSheet("background:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.989, stop:0.0738636 rgba(255, 255, 255, 0))")
        self.textBrowser_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_5.setLineWidth(0)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_6.setGeometry(QtCore.QRect(70, 150, 51, 21))
        self.textBrowser_6.setAutoFillBackground(True)
        self.textBrowser_6.setStyleSheet("background:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.989, stop:0.0738636 rgba(255, 255, 255, 0))")
        self.textBrowser_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_6.setLineWidth(0)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_7.setGeometry(QtCore.QRect(70, 120, 51, 21))
        self.textBrowser_7.setAutoFillBackground(True)
        self.textBrowser_7.setStyleSheet("background:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.989, stop:0.0738636 rgba(255, 255, 255, 0))")
        self.textBrowser_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_7.setLineWidth(0)
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_8.setGeometry(QtCore.QRect(70, 90, 51, 21))
        self.textBrowser_8.setAutoFillBackground(False)
        self.textBrowser_8.setStyleSheet("background:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.989, stop:0.0738636 rgba(255, 255, 255, 0))")
        self.textBrowser_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_8.setLineWidth(0)
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_9.setGeometry(QtCore.QRect(10, 60, 111, 21))
        self.textBrowser_9.setAutoFillBackground(False)
        self.textBrowser_9.setStyleSheet("background:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.989, stop:0.0738636 rgba(255, 255, 255, 0))")
        self.textBrowser_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_9.setLineWidth(0)
        self.textBrowser_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_9.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_10.setGeometry(QtCore.QRect(10, 270, 111, 21))
        self.textBrowser_10.setAutoFillBackground(True)
        self.textBrowser_10.setStyleSheet("background:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0.989, stop:0.0738636 rgba(255, 255, 255, 0))")
        self.textBrowser_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_10.setLineWidth(0)
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.horizontalLayout_14.addWidget(self.groupBox_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.line_4 = QtWidgets.QFrame(self.tab_i_graphics)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_9.addWidget(self.line_4)
        self.label = QtWidgets.QLabel(self.tab_i_graphics)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.tableView_instance_stats = QtWidgets.QTableView(self.tab_i_graphics)
        self.tableView_instance_stats.setAlternatingRowColors(True)
        self.tableView_instance_stats.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableView_instance_stats.setObjectName("tableView_instance_stats")
        self.tableView_instance_stats.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView_instance_stats.horizontalHeader().setSortIndicatorShown(True)
        self.tableView_instance_stats.horizontalHeader().setStretchLastSection(False)
        self.tableView_instance_stats.verticalHeader().setCascadingSectionResizes(True)
        self.tableView_instance_stats.verticalHeader().setSortIndicatorShown(False)
        self.tableView_instance_stats.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_9.addWidget(self.tableView_instance_stats)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.tabWidget_instance.addTab(self.tab_i_graphics, "")
        self.tab_i_spreadsheet = QtWidgets.QWidget()
        self.tab_i_spreadsheet.setObjectName("tab_i_spreadsheet")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_i_spreadsheet)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView_parameters_jobs = QtWidgets.QTableView(self.tab_i_spreadsheet)
        self.tableView_parameters_jobs.setAlternatingRowColors(True)
        self.tableView_parameters_jobs.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableView_parameters_jobs.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_parameters_jobs.setSortingEnabled(True)
        self.tableView_parameters_jobs.setObjectName("tableView_parameters_jobs")
        self.tableView_parameters_jobs.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView_parameters_jobs.verticalHeader().setCascadingSectionResizes(True)
        self.tableView_parameters_jobs.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_3.addWidget(self.tableView_parameters_jobs)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.tabWidget_instance.addTab(self.tab_i_spreadsheet, "")
        self.tab_i_setup = QtWidgets.QWidget()
        self.tab_i_setup.setObjectName("tab_i_setup")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_i_setup)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableView_parameters_setup = QtWidgets.QTableView(self.tab_i_setup)
        self.tableView_parameters_setup.setAlternatingRowColors(True)
        self.tableView_parameters_setup.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_parameters_setup.setSortingEnabled(True)
        self.tableView_parameters_setup.setObjectName("tableView_parameters_setup")
        self.verticalLayout_5.addWidget(self.tableView_parameters_setup)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_i_setup)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.lineEdit_initial_setup = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_initial_setup.setEnabled(True)
        self.lineEdit_initial_setup.setMinimumSize(QtCore.QSize(25, 20))
        self.lineEdit_initial_setup.setMaximumSize(QtCore.QSize(25, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_initial_setup.setFont(font)
        self.lineEdit_initial_setup.setAutoFillBackground(False)
        self.lineEdit_initial_setup.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";background-color:rgb(208, 208, 208)")
        self.lineEdit_initial_setup.setText("")
        self.lineEdit_initial_setup.setFrame(True)
        self.lineEdit_initial_setup.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_initial_setup.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_initial_setup.setReadOnly(True)
        self.lineEdit_initial_setup.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_initial_setup.setClearButtonEnabled(False)
        self.lineEdit_initial_setup.setObjectName("lineEdit_initial_setup")
        self.horizontalLayout_13.addWidget(self.lineEdit_initial_setup)
        spacerItem = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout_5.addWidget(self.groupBox_7)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.tabWidget_instance.addTab(self.tab_i_setup, "")
        self.tab_i_csv = QtWidgets.QWidget()
        self.tab_i_csv.setObjectName("tab_i_csv")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_i_csv)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_i_csv)
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_4.addWidget(self.plainTextEdit)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.tabWidget_instance.addTab(self.tab_i_csv, "")
        self.horizontalLayout_6.addWidget(self.tabWidget_instance)
        self.tabWidget_master.addTab(self.tab_instance, "")
        self.tab_results = QtWidgets.QWidget()
        self.tab_results.setObjectName("tab_results")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.tab_results)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget_results = QtWidgets.QTabWidget(self.tab_results)
        self.tabWidget_results.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_results.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_results.setMovable(True)
        self.tabWidget_results.setObjectName("tabWidget_results")
        self.tab_r_spreadsheet = QtWidgets.QWidget()
        self.tab_r_spreadsheet.setObjectName("tab_r_spreadsheet")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_r_spreadsheet)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.tableView_results = QtWidgets.QTableView(self.tab_r_spreadsheet)
        self.tableView_results.setAlternatingRowColors(True)
        self.tableView_results.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_results.setSortingEnabled(True)
        self.tableView_results.setObjectName("tableView_results")
        self.horizontalLayout_12.addWidget(self.tableView_results)
        self.tabWidget_results.addTab(self.tab_r_spreadsheet, "")
        self.tab_r_chart = QtWidgets.QWidget()
        self.tab_r_chart.setObjectName("tab_r_chart")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.tab_r_chart)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_results = QtWidgets.QVBoxLayout()
        self.verticalLayout_results.setObjectName("verticalLayout_results")
        self.horizontalLayout_15.addLayout(self.verticalLayout_results)
        self.tabWidget_results.addTab(self.tab_r_chart, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tableView_performance = QtWidgets.QTableView(self.tab_6)
        self.tableView_performance.setMinimumSize(QtCore.QSize(0, 400))
        self.tableView_performance.setAlternatingRowColors(True)
        self.tableView_performance.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_performance.setSortingEnabled(True)
        self.tableView_performance.setCornerButtonEnabled(True)
        self.tableView_performance.setObjectName("tableView_performance")
        self.tableView_performance.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView_performance.horizontalHeader().setSortIndicatorShown(True)
        self.tableView_performance.horizontalHeader().setStretchLastSection(False)
        self.tableView_performance.verticalHeader().setVisible(False)
        self.tableView_performance.verticalHeader().setCascadingSectionResizes(False)
        self.tableView_performance.verticalHeader().setSortIndicatorShown(False)
        self.tableView_performance.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_12.addWidget(self.tableView_performance)
        self.label_2 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_12.addWidget(self.label_2)
        self.textBrowser_f_description = QtWidgets.QTextBrowser(self.tab_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_f_description.setFont(font)
        self.textBrowser_f_description.setObjectName("textBrowser_f_description")
        self.verticalLayout_12.addWidget(self.textBrowser_f_description)
        self.tabWidget_results.addTab(self.tab_6, "")
        self.verticalLayout_7.addWidget(self.tabWidget_results)
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.tabWidget_master.addTab(self.tab_results, "")
        self.tab_al = QtWidgets.QWidget()
        self.tab_al.setObjectName("tab_al")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_al)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget_algorithm = QtWidgets.QTabWidget(self.tab_al)
        self.tabWidget_algorithm.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_algorithm.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_algorithm.setMovable(True)
        self.tabWidget_algorithm.setObjectName("tabWidget_algorithm")
        self.tab_a_executions = QtWidgets.QWidget()
        self.tab_a_executions.setObjectName("tab_a_executions")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_a_executions)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.tab_a_executions)
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.verticalLayout_10.addWidget(self.textBrowser_11)
        self.tabWidget_algorithm.addTab(self.tab_a_executions, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_ig = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ig.sizePolicy().hasHeightForWidth())
        self.label_ig.setSizePolicy(sizePolicy)
        self.label_ig.setText("")
        self.label_ig.setObjectName("label_ig")
        self.horizontalLayout_17.addWidget(self.label_ig)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_destroy = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_destroy.sizePolicy().hasHeightForWidth())
        self.label_destroy.setSizePolicy(sizePolicy)
        self.label_destroy.setText("")
        self.label_destroy.setObjectName("label_destroy")
        self.verticalLayout_11.addWidget(self.label_destroy)
        self.horizontalLayout_18.addLayout(self.verticalLayout_11)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_insert = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_insert.sizePolicy().hasHeightForWidth())
        self.label_insert.setSizePolicy(sizePolicy)
        self.label_insert.setText("")
        self.label_insert.setObjectName("label_insert")
        self.horizontalLayout_16.addWidget(self.label_insert)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_exchange = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_exchange.sizePolicy().hasHeightForWidth())
        self.label_exchange.setSizePolicy(sizePolicy)
        self.label_exchange.setText("")
        self.label_exchange.setObjectName("label_exchange")
        self.horizontalLayout_19.addWidget(self.label_exchange)
        self.tabWidget.addTab(self.tab_5, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_5)
        self.tabWidget_algorithm.addTab(self.tab, "")
        self.verticalLayout_6.addWidget(self.tabWidget_algorithm)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.tabWidget_master.addTab(self.tab_al, "")
        self.verticalLayout_2.addWidget(self.tabWidget_master)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1197, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_par = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_par.setMinimumSize(QtCore.QSize(520, 400))
        self.dockWidget_par.setMaximumSize(QtCore.QSize(520, 400))
        self.dockWidget_par.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_par.setWindowTitle("")
        self.dockWidget_par.setObjectName("dockWidget_par")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_6.setGeometry(QtCore.QRect(230, 20, 71, 20))
        self.label_6.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_7.setGeometry(QtCore.QRect(420, 10, 41, 16))
        self.label_7.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_5.setGeometry(QtCore.QRect(240, 60, 271, 261))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(0, 30, 111, 20))
        self.label_11.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.lineEdit_res_runtime = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_res_runtime.setEnabled(True)
        self.lineEdit_res_runtime.setGeometry(QtCore.QRect(120, 60, 111, 20))
        self.lineEdit_res_runtime.setAutoFillBackground(False)
        self.lineEdit_res_runtime.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";background-color:rgb(225, 225, 225);")
        self.lineEdit_res_runtime.setText("")
        self.lineEdit_res_runtime.setFrame(True)
        self.lineEdit_res_runtime.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_res_runtime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_res_runtime.setReadOnly(True)
        self.lineEdit_res_runtime.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_res_runtime.setClearButtonEnabled(False)
        self.lineEdit_res_runtime.setObjectName("lineEdit_res_runtime")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(40, 60, 71, 20))
        self.label_10.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.lineEdit_res_candidate = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_res_candidate.setEnabled(True)
        self.lineEdit_res_candidate.setGeometry(QtCore.QRect(120, 30, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_res_candidate.setFont(font)
        self.lineEdit_res_candidate.setAutoFillBackground(False)
        self.lineEdit_res_candidate.setStyleSheet("background-color:rgb(225, 225, 225);\n"
"font: 12pt \"Sans Serif\";")
        self.lineEdit_res_candidate.setFrame(True)
        self.lineEdit_res_candidate.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_res_candidate.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_res_candidate.setReadOnly(True)
        self.lineEdit_res_candidate.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_res_candidate.setClearButtonEnabled(False)
        self.lineEdit_res_candidate.setObjectName("lineEdit_res_candidate")
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(10, 160, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.lineEdit_res_improv = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_res_improv.setEnabled(True)
        self.lineEdit_res_improv.setGeometry(QtCore.QRect(190, 160, 41, 20))
        self.lineEdit_res_improv.setAutoFillBackground(False)
        self.lineEdit_res_improv.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";background-color:rgb(225, 225, 225);")
        self.lineEdit_res_improv.setText("")
        self.lineEdit_res_improv.setFrame(True)
        self.lineEdit_res_improv.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_res_improv.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_res_improv.setReadOnly(True)
        self.lineEdit_res_improv.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_res_improv.setClearButtonEnabled(False)
        self.lineEdit_res_improv.setObjectName("lineEdit_res_improv")
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(40, 100, 71, 20))
        self.label_22.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.lineEdit_res_iterations = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_res_iterations.setEnabled(True)
        self.lineEdit_res_iterations.setGeometry(QtCore.QRect(120, 100, 111, 20))
        self.lineEdit_res_iterations.setAutoFillBackground(False)
        self.lineEdit_res_iterations.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";background-color:rgb(225, 225, 225);")
        self.lineEdit_res_iterations.setText("")
        self.lineEdit_res_iterations.setFrame(True)
        self.lineEdit_res_iterations.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_res_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_res_iterations.setReadOnly(True)
        self.lineEdit_res_iterations.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_res_iterations.setClearButtonEnabled(False)
        self.lineEdit_res_iterations.setObjectName("lineEdit_res_iterations")
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(240, 130, 20, 20))
        self.label_28.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(240, 160, 20, 20))
        self.label_29.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_29.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.lineEdit_res_gap = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_res_gap.setEnabled(True)
        self.lineEdit_res_gap.setGeometry(QtCore.QRect(190, 130, 41, 20))
        self.lineEdit_res_gap.setAutoFillBackground(False)
        self.lineEdit_res_gap.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";background-color:rgb(225, 225, 225);")
        self.lineEdit_res_gap.setText("")
        self.lineEdit_res_gap.setFrame(True)
        self.lineEdit_res_gap.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_res_gap.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_res_gap.setReadOnly(True)
        self.lineEdit_res_gap.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_res_gap.setClearButtonEnabled(False)
        self.lineEdit_res_gap.setObjectName("lineEdit_res_gap")
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(20, 130, 161, 20))
        self.label_21.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(240, 60, 21, 20))
        self.label_30.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.lineEdit_res_perf = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_res_perf.setEnabled(True)
        self.lineEdit_res_perf.setGeometry(QtCore.QRect(190, 200, 41, 20))
        self.lineEdit_res_perf.setAutoFillBackground(False)
        self.lineEdit_res_perf.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";background-color:rgb(225, 225, 225);")
        self.lineEdit_res_perf.setFrame(True)
        self.lineEdit_res_perf.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_res_perf.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_res_perf.setReadOnly(True)
        self.lineEdit_res_perf.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_res_perf.setClearButtonEnabled(False)
        self.lineEdit_res_perf.setObjectName("lineEdit_res_perf")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(60, 230, 121, 20))
        self.label_20.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.lineEdit_res_unperf = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_res_unperf.setEnabled(True)
        self.lineEdit_res_unperf.setGeometry(QtCore.QRect(190, 230, 41, 20))
        self.lineEdit_res_unperf.setAutoFillBackground(False)
        self.lineEdit_res_unperf.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";background-color:rgb(225, 225, 225);")
        self.lineEdit_res_unperf.setText("")
        self.lineEdit_res_unperf.setFrame(True)
        self.lineEdit_res_unperf.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_res_unperf.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_res_unperf.setReadOnly(True)
        self.lineEdit_res_unperf.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_res_unperf.setClearButtonEnabled(False)
        self.lineEdit_res_unperf.setObjectName("lineEdit_res_unperf")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(70, 200, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.line_5 = QtWidgets.QFrame(self.groupBox_5)
        self.line_5.setGeometry(QtCore.QRect(0, 80, 271, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.groupBox_5)
        self.line_6.setGeometry(QtCore.QRect(0, 180, 271, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 320, 211, 41))
        self.groupBox_4.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBox_permutation = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_permutation.setGeometry(QtCore.QRect(20, 20, 91, 17))
        self.checkBox_permutation.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.checkBox_permutation.setChecked(True)
        self.checkBox_permutation.setObjectName("checkBox_permutation")
        self.lineEdit_tardiness = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.lineEdit_tardiness.setEnabled(True)
        self.lineEdit_tardiness.setGeometry(QtCore.QRect(470, 30, 31, 16))
        self.lineEdit_tardiness.setAutoFillBackground(False)
        self.lineEdit_tardiness.setStyleSheet("font: 10pt \"Sans Serif\";\n"
"background-color:rgb(225, 225, 225);")
        self.lineEdit_tardiness.setFrame(True)
        self.lineEdit_tardiness.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_tardiness.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tardiness.setReadOnly(True)
        self.lineEdit_tardiness.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_tardiness.setClearButtonEnabled(False)
        self.lineEdit_tardiness.setObjectName("lineEdit_tardiness")
        self.line_2 = QtWidgets.QFrame(self.dockWidgetContents_2)
        self.line_2.setGeometry(QtCore.QRect(220, 50, 20, 311))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_status = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_status.setGeometry(QtCore.QRect(240, 60, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("background:rgb(225, 225, 225);\n"
"font: 11pt \"Sans Serif\";")
        self.label_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_status.setTextFormat(QtCore.Qt.AutoText)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.label_13 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_13.setGeometry(QtCore.QRect(360, 30, 101, 20))
        self.label_13.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.groupBox_stop_criterion = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_stop_criterion.setGeometry(QtCore.QRect(10, 60, 211, 91))
        self.groupBox_stop_criterion.setObjectName("groupBox_stop_criterion")
        self.lineEdit_time_limit = QtWidgets.QLineEdit(self.groupBox_stop_criterion)
        self.lineEdit_time_limit.setGeometry(QtCore.QRect(100, 60, 71, 20))
        self.lineEdit_time_limit.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";background:rgb(255, 252, 240)")
        self.lineEdit_time_limit.setObjectName("lineEdit_time_limit")
        self.label_4 = QtWidgets.QLabel(self.groupBox_stop_criterion)
        self.label_4.setGeometry(QtCore.QRect(0, 60, 91, 16))
        self.label_4.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_stop_criterion)
        self.label_3.setGeometry(QtCore.QRect(0, 30, 91, 20))
        self.label_3.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_best_solution = QtWidgets.QLineEdit(self.groupBox_stop_criterion)
        self.lineEdit_best_solution.setGeometry(QtCore.QRect(100, 30, 71, 20))
        self.lineEdit_best_solution.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";background:rgb(255, 252, 240)")
        self.lineEdit_best_solution.setObjectName("lineEdit_best_solution")
        self.label_31 = QtWidgets.QLabel(self.groupBox_stop_criterion)
        self.label_31.setGeometry(QtCore.QRect(180, 60, 21, 20))
        self.label_31.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.groupBox_3 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 160, 211, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_candidate = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_candidate.setGeometry(QtCore.QRect(10, 20, 181, 17))
        self.radioButton_candidate.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.radioButton_candidate.setChecked(True)
        self.radioButton_candidate.setObjectName("radioButton_candidate")
        self.radioButton_iterated = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_iterated.setGeometry(QtCore.QRect(10, 40, 161, 17))
        self.radioButton_iterated.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.radioButton_iterated.setObjectName("radioButton_iterated")
        self.lineEdit_setup = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.lineEdit_setup.setEnabled(True)
        self.lineEdit_setup.setGeometry(QtCore.QRect(470, 10, 31, 16))
        self.lineEdit_setup.setAutoFillBackground(False)
        self.lineEdit_setup.setStyleSheet("font: 10pt \"Sans Serif\";;background-color:rgb(225, 225, 225);")
        self.lineEdit_setup.setFrame(True)
        self.lineEdit_setup.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_setup.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_setup.setReadOnly(True)
        self.lineEdit_setup.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_setup.setClearButtonEnabled(False)
        self.lineEdit_setup.setObjectName("lineEdit_setup")
        self.lineEdit_jobs = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.lineEdit_jobs.setEnabled(True)
        self.lineEdit_jobs.setGeometry(QtCore.QRect(310, 20, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_jobs.setFont(font)
        self.lineEdit_jobs.setAutoFillBackground(False)
        self.lineEdit_jobs.setStyleSheet("font: 10pt \"Sans Serif\";;background-color:rgb(225, 225, 225);")
        self.lineEdit_jobs.setFrame(True)
        self.lineEdit_jobs.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_jobs.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_jobs.setReadOnly(True)
        self.lineEdit_jobs.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_jobs.setClearButtonEnabled(False)
        self.lineEdit_jobs.setObjectName("lineEdit_jobs")
        self.pushButton_run = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.pushButton_run.setGeometry(QtCore.QRect(320, 330, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_run.setFont(font)
        self.pushButton_run.setStyleSheet("background:rgb(217, 217, 217); font: 14pt \"Sans Serif\";")
        self.pushButton_run.setCheckable(False)
        self.pushButton_run.setAutoDefault(False)
        self.pushButton_run.setDefault(False)
        self.pushButton_run.setFlat(False)
        self.pushButton_run.setObjectName("pushButton_run")
        self.line = QtWidgets.QFrame(self.dockWidgetContents_2)
        self.line.setGeometry(QtCore.QRect(10, 40, 501, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label_instance = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_instance.setGeometry(QtCore.QRect(20, 20, 71, 21))
        self.label_instance.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_instance.setObjectName("label_instance")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 230, 211, 81))
        self.groupBox.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.groupBox.setObjectName("groupBox")
        self.radioButton_fixed = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_fixed.setGeometry(QtCore.QRect(10, 20, 51, 17))
        self.radioButton_fixed.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.radioButton_fixed.setChecked(True)
        self.radioButton_fixed.setObjectName("radioButton_fixed")
        self.radioButton_random = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_random.setGeometry(QtCore.QRect(10, 40, 71, 17))
        self.radioButton_random.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.radioButton_random.setObjectName("radioButton_random")
        self.spinBox_r_min = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_r_min.setGeometry(QtCore.QRect(150, 20, 31, 16))
        self.spinBox_r_min.setFrame(False)
        self.spinBox_r_min.setMinimum(1)
        self.spinBox_r_min.setMaximum(10000)
        self.spinBox_r_min.setObjectName("spinBox_r_min")
        self.spinBox_r_max = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_r_max.setGeometry(QtCore.QRect(150, 40, 31, 16))
        self.spinBox_r_max.setFrame(False)
        self.spinBox_r_max.setKeyboardTracking(True)
        self.spinBox_r_max.setProperty("showGroupSeparator", False)
        self.spinBox_r_max.setMinimum(1)
        self.spinBox_r_max.setMaximum(10000)
        self.spinBox_r_max.setProperty("value", 6)
        self.spinBox_r_max.setDisplayIntegerBase(10)
        self.spinBox_r_max.setObjectName("spinBox_r_max")
        self.spinBox_fixed = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_fixed.setGeometry(QtCore.QRect(70, 20, 31, 16))
        self.spinBox_fixed.setWrapping(False)
        self.spinBox_fixed.setFrame(False)
        self.spinBox_fixed.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_fixed.setMinimum(1)
        self.spinBox_fixed.setMaximum(10000)
        self.spinBox_fixed.setProperty("value", 2)
        self.spinBox_fixed.setObjectName("spinBox_fixed")
        self.label_min = QtWidgets.QLabel(self.groupBox)
        self.label_min.setGeometry(QtCore.QRect(110, 20, 31, 20))
        self.label_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_min.setObjectName("label_min")
        self.label_max = QtWidgets.QLabel(self.groupBox)
        self.label_max.setGeometry(QtCore.QRect(110, 40, 31, 20))
        self.label_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_max.setObjectName("label_max")
        self.radioButton_triangular = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_triangular.setGeometry(QtCore.QRect(10, 60, 81, 17))
        self.radioButton_triangular.setStyleSheet("font: 9pt \"Sans Serif\";")
        self.radioButton_triangular.setChecked(False)
        self.radioButton_triangular.setObjectName("radioButton_triangular")
        self.label_mode = QtWidgets.QLabel(self.groupBox)
        self.label_mode.setGeometry(QtCore.QRect(90, 60, 51, 16))
        self.label_mode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mode.setObjectName("label_mode")
        self.spinBox_r_mode = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_r_mode.setGeometry(QtCore.QRect(150, 60, 31, 16))
        self.spinBox_r_mode.setFrame(False)
        self.spinBox_r_mode.setKeyboardTracking(True)
        self.spinBox_r_mode.setProperty("showGroupSeparator", False)
        self.spinBox_r_mode.setMinimum(1)
        self.spinBox_r_mode.setMaximum(10000)
        self.spinBox_r_mode.setProperty("value", 2)
        self.spinBox_r_mode.setDisplayIntegerBase(10)
        self.spinBox_r_mode.setObjectName("spinBox_r_mode")
        self.comboBox_instance = QtWidgets.QComboBox(self.dockWidgetContents_2)
        self.comboBox_instance.setGeometry(QtCore.QRect(90, 20, 131, 21))
        self.comboBox_instance.setStyleSheet("")
        self.comboBox_instance.setEditable(False)
        self.comboBox_instance.setCurrentText("")
        self.comboBox_instance.setMaxVisibleItems(10)
        self.comboBox_instance.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_instance.setMinimumContentsLength(0)
        self.comboBox_instance.setObjectName("comboBox_instance")
        self.line_7 = QtWidgets.QFrame(self.dockWidgetContents_2)
        self.line_7.setGeometry(QtCore.QRect(10, -10, 501, 21))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.dockWidgetContents_2)
        self.line_8.setGeometry(QtCore.QRect(500, 0, 20, 51))
        self.line_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.dockWidgetContents_2)
        self.line_9.setGeometry(QtCore.QRect(0, 0, 20, 51))
        self.line_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setObjectName("line_9")
        self.dockWidget_par.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_par)
        self.dockWidget_l = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_l.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_l.setObjectName("dockWidget_l")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableView_log = QtWidgets.QTableView(self.dockWidgetContents_3)
        self.tableView_log.setDragEnabled(False)
        self.tableView_log.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableView_log.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableView_log.setAlternatingRowColors(True)
        self.tableView_log.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableView_log.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_log.setSortingEnabled(True)
        self.tableView_log.setObjectName("tableView_log")
        self.tableView_log.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView_log.horizontalHeader().setSortIndicatorShown(True)
        self.tableView_log.horizontalHeader().setStretchLastSection(False)
        self.tableView_log.verticalHeader().setCascadingSectionResizes(False)
        self.tableView_log.verticalHeader().setSortIndicatorShown(False)
        self.tableView_log.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_8.addWidget(self.tableView_log)
        self.dockWidget_l.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_l)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionIG_Project = QtWidgets.QAction(MainWindow)
        self.actionIG_Project.setObjectName("actionIG_Project")
        self.actionBugs_Feedback = QtWidgets.QAction(MainWindow)
        self.actionBugs_Feedback.setObjectName("actionBugs_Feedback")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionIG_Project)
        self.menuHelp.addAction(self.actionBugs_Feedback)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_master.setCurrentIndex(0)
        self.tabWidget_instance.setCurrentIndex(0)
        self.tabWidget_results.setCurrentIndex(0)
        self.tabWidget_algorithm.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_instance.setCurrentIndex(-1)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget_instance, self.tableView_instance_stats)
        MainWindow.setTabOrder(self.tableView_instance_stats, self.tableView_parameters_jobs)
        MainWindow.setTabOrder(self.tableView_parameters_jobs, self.plainTextEdit)
        MainWindow.setTabOrder(self.plainTextEdit, self.tableView_parameters_setup)
        MainWindow.setTabOrder(self.tableView_parameters_setup, self.lineEdit_initial_setup)
        MainWindow.setTabOrder(self.lineEdit_initial_setup, self.tabWidget_results)
        MainWindow.setTabOrder(self.tabWidget_results, self.tableView_results)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Metaheuristic Iterated Greed for Manufacturing Schedule Problem"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Histograms -  Axis Y = Jobs     "))
        self.groupBox_8.setTitle(_translate("MainWindow", "Gap Benchmarks"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">GAP</span> = 100 * (Found - Best) / Best </p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Format = Average GAP of 5 Runs (min - max)</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Ama</span><span style=\" font-size:8pt; vertical-align:super;\">sp</span><span style=\" font-size:8pt;\">:</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Ama</span><span style=\" font-size:8pt; vertical-align:super;\">mem</span><span style=\" font-size:8pt;\">:</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">TabuDiv:</span></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Tabu:</span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Descent:</span></p></body></html>"))
        self.textBrowser_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Greedy:</span></p></body></html>"))
        self.textBrowser_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Linear Programming:</span></p></body></html>"))
        self.textBrowser_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Iterated Greedy:</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Descriptive Statistical Analisys"))
        self.tabWidget_instance.setTabText(self.tabWidget_instance.indexOf(self.tab_i_graphics), _translate("MainWindow", "Info"))
        self.tabWidget_instance.setTabText(self.tabWidget_instance.indexOf(self.tab_i_spreadsheet), _translate("MainWindow", "Jobs Parameters"))
        self.label_9.setText(_translate("MainWindow", "Initial Setup State:"))
        self.tabWidget_instance.setTabText(self.tabWidget_instance.indexOf(self.tab_i_setup), _translate("MainWindow", "Setup Parameters"))
        self.tabWidget_instance.setTabText(self.tabWidget_instance.indexOf(self.tab_i_csv), _translate("MainWindow", "Instance.csv"))
        self.tabWidget_master.setTabText(self.tabWidget_master.indexOf(self.tab_instance), _translate("MainWindow", "Instance"))
        self.tabWidget_results.setTabText(self.tabWidget_results.indexOf(self.tab_r_spreadsheet), _translate("MainWindow", "Spreadsheet"))
        self.tabWidget_results.setTabText(self.tabWidget_results.indexOf(self.tab_r_chart), _translate("MainWindow", "Runtime Chart"))
        self.label_2.setText(_translate("MainWindow", "Function Description: (Double click on the function name to access)"))
        self.textBrowser_f_description.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:400;\"><br /></p></body></html>"))
        self.tabWidget_results.setTabText(self.tabWidget_results.indexOf(self.tab_6), _translate("MainWindow", "Algorithm Timer"))
        self.tabWidget_master.setTabText(self.tabWidget_master.indexOf(self.tab_results), _translate("MainWindow", "Results"))
        self.textBrowser_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">A Iterated Greedy algorithm applied in scheduling with rejection and tardiness penalties.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In classical scheduling problems, it is assumed that all jobs are to be processed. However, in many practical cases, especially on make-to-order production systems, accept all requests may cause a delay in the completion of orders, leading to higher inventory costs and customer dissatisfaction. For be more similar to real problems, the study of scheduling with rejection has received great attention by researchers in the past decade. This study aimed to develop an algorithm based on Iterated Greedy technique and apply it in a scheduling problem with rejection and tardiness penalties, in a single machine environment, comparing the results with those found by other metaheuristics in the literature. From mathematical models that simulate the functioning of productive systems, the algorithm must decide what job should or should not be done by setting a schedule so that all constraints of the problem are obeyed and the optimization criterion is minimized. The optimization criterion is a linear combination of the sum of the jobs processed costs (other than processing costs, setup costs and tardiness costs may occur), and the sum of rejection costs of unprocessed jobs. The results found by the algorithm proposed (in terms of results and computational time) were equivalent to the results obtained by the metaheuristics in the literature. Regarding the 44 instances tested, 36 had results equal to optimal solution in the literature, 2 had better than optimal solution and the rest obtained results close to optimal. </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Metaheuristic developed by <span style=\" font-weight:600;\">Alex Marinho. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">alexmarinho@gmail.com</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Links:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">MascLib instances developed by ILOG (now part of IBM):</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www-01.ibm.com/software/info/ilog/\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">Ilog Website</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; text-decoration: underline; color:#0000ff;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; text-decoration: underline; color:#0000ff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www-01.ibm.com/software/info/ilog/\"><span style=\" font-size:8pt; font-weight:600; text-decoration: underline; color:#000000;\">Articles: </span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.researchgate.net/publication/281228499_Towards_an_industrial_Manufacturing_Scheduling_Problem_and_Test_Bed\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">About MascLib instances (2004)</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.sciencedirect.com/science/article/pii/S0377221706008277\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">First Iterated Greedy algorithm proposed by Ruiz and Stützle (2005)</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://link.springer.com/article/10.1007/s10951-014-0395-8\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">Benchmark for MascLib  Thevenin, Zufferey, Widmer (2015)</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Free knowledge for ALL!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://sci-hub.io\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">Sci-hub</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget_algorithm.setTabText(self.tabWidget_algorithm.indexOf(self.tab_a_executions), _translate("MainWindow", "Description"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Iterated Greedy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Destroy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Insert"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Swap"))
        self.tabWidget_algorithm.setTabText(self.tabWidget_algorithm.indexOf(self.tab), _translate("MainWindow", "Flowcharts"))
        self.tabWidget_master.setTabText(self.tabWidget_master.indexOf(self.tab_al), _translate("MainWindow", "About"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.label_6.setText(_translate("MainWindow", "Total Jobs:"))
        self.label_7.setText(_translate("MainWindow", "Setup:"))
        self.label_11.setText(_translate("MainWindow", "Solution Founded:"))
        self.label_10.setText(_translate("MainWindow", "Runtime:"))
        self.label_23.setText(_translate("MainWindow", "Cost saving over 1º Solution:"))
        self.label_22.setText(_translate("MainWindow", "Iterations:"))
        self.label_28.setText(_translate("MainWindow", "%"))
        self.label_29.setText(_translate("MainWindow", "%"))
        self.label_21.setText(_translate("MainWindow", "Gap over Best Solution:"))
        self.label_30.setText(_translate("MainWindow", "sec"))
        self.label_20.setText(_translate("MainWindow", "Unperformed Jobs:"))
        self.label_12.setText(_translate("MainWindow", "Performed Jobs:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Algorithm Functionalities:"))
        self.checkBox_permutation.setText(_translate("MainWindow", "Swap"))
        self.label_status.setText(_translate("MainWindow", "Results"))
        self.label_13.setText(_translate("MainWindow", " Penalty Weight:"))
        self.groupBox_stop_criterion.setTitle(_translate("MainWindow", "Stopping Condition:"))
        self.label_4.setText(_translate("MainWindow", "Max Runtime:"))
        self.label_3.setText(_translate("MainWindow", "Best Solution:"))
        self.label_31.setText(_translate("MainWindow", "sec"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Solution to be destroyed:"))
        self.radioButton_candidate.setText(_translate("MainWindow", "Best during Runtime"))
        self.radioButton_iterated.setText(_translate("MainWindow", "Best during iteration"))
        self.pushButton_run.setText(_translate("MainWindow", "Run"))
        self.label_instance.setText(_translate("MainWindow", "Instance:"))
        self.groupBox.setTitle(_translate("MainWindow", "Jobs to be destroyed:"))
        self.radioButton_fixed.setText(_translate("MainWindow", "Fixed"))
        self.radioButton_random.setText(_translate("MainWindow", "Random"))
        self.label_min.setText(_translate("MainWindow", "Min:"))
        self.label_max.setText(_translate("MainWindow", "Max:"))
        self.radioButton_triangular.setText(_translate("MainWindow", "Triangular"))
        self.label_mode.setText(_translate("MainWindow", "Mode:"))
        self.dockWidget_l.setWindowTitle(_translate("MainWindow", "Runtime Solutions Found"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionIG_Project.setText(_translate("MainWindow", "IG Project"))
        self.actionBugs_Feedback.setText(_translate("MainWindow", "Bugs & Feedback"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

