#!/usr/bin/env node
/** Build the self-contained Apps Script WebAssembly + instance payload. */
import { gzipSync } from 'node:zlib';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..', '..');
const output = path.join(root, 'google-sheets', 'generated', 'Payload.gs');
const wasmPath = path.join(
  root,
  'engine',
  'target',
  'wasm32-unknown-unknown',
  'release',
  'ig_core.wasm',
);

const benchmark = JSON.parse(await readFile(path.join(root, 'benchmark.json'), 'utf8'));
const directories = ['masclib', 'masclib-gpu'];
const catalog = {};

// Job count = number of MODE data rows (one activity per row; the engine rejects
// multi-mode files). Precomputing this lets the sidebar bootstrap skip a full
// CSV re-parse for instances absent from benchmark.json (the GPU_ workloads).
function countJobs(csv) {
  let jobs = 0;
  for (const line of csv.split('\n')) {
    if (line.slice(0, 5) === 'MODE,') jobs += 1;
  }
  return jobs;
}

for (const directory of directories) {
  const absolute = path.join(root, directory);
  const files = (await readdir(absolute)).filter((name) => name.endsWith('.csv')).sort();
  for (const filename of files) {
    const name = path.basename(filename, '.csv');
    const known = benchmark[name];
    const csv = await readFile(path.join(absolute, filename), 'utf8');
    catalog[name] = {
      csv: csv,
      metadata: {
        jobs: known ? known[0] : countJobs(csv),
        bestKnown: known ? known[1] : null,
        dataset: directory === 'masclib' ? 'MaScLib' : 'Bundled workload',
        family: name.startsWith('GPU_')
          ? 'gpu'
          : name.startsWith('STC_')
            ? 'setup'
            : 'standard',
      },
    };
  }
}

const wasm = await readFile(wasmPath);
// Split payload: a small plain-JSON metadata map the sidebar bootstrap can read
// on its own, plus one gzipped CSV per instance decoded only when a run needs
// it. Previously every bootstrap ungzipped and parsed the whole catalog just to
// list ~5 KB of metadata.
const names = Object.keys(catalog).sort();
const catalogMeta = {};
const instances = {};
for (const name of names) {
  catalogMeta[name] = catalog[name].metadata;
  instances[name] = gzipSync(Buffer.from(catalog[name].csv), { level: 9, mtime: 0 }).toString('base64');
}
const catalogMetaJson = JSON.stringify(catalogMeta);
const instanceLines = names.map(
  (name, index) => `    ${JSON.stringify(name)}: ${JSON.stringify(instances[name])}${index === names.length - 1 ? '' : ','}`,
);
const source = [
  '/* Generated by google-sheets/scripts/build-payload.mjs. */',
  'var IG_PAYLOAD = Object.freeze({',
  `  wasmBase64: ${JSON.stringify(wasm.toString('base64'))},`,
  `  catalogMetaJson: ${JSON.stringify(catalogMetaJson)},`,
  '  instanceGzipBase64: Object.freeze({',
  ...instanceLines,
  '  }),',
  `  wasmBytes: ${wasm.length},`,
  `  catalogEntries: ${names.length}`,
  '});',
  '',
].join('\n');

await mkdir(path.dirname(output), { recursive: true });
await writeFile(output, source);
console.log(JSON.stringify({
  output,
  wasmBytes: wasm.length,
  catalogEntries: names.length,
  catalogMetaBytes: Buffer.byteLength(catalogMetaJson),
  instanceGzipBytes: Object.values(instances).reduce((sum, b64) => sum + b64.length, 0),
  sourceBytes: Buffer.byteLength(source),
}));
