#!/usr/bin/env node
/** Build the self-contained Apps Script WebAssembly + instance payload. */
import { gzipSync } from 'node:zlib';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..', '..');
const output = path.join(root, 'google-sheets', 'generated', 'Payload.gs');
const wasmPath = path.join(
  root,
  'engine',
  'target',
  'wasm32-unknown-unknown',
  'release',
  'ig_core.wasm',
);

const benchmark = JSON.parse(await readFile(path.join(root, 'benchmark.json'), 'utf8'));
const directories = ['masclib', 'masclib-gpu'];
const catalog = {};

for (const directory of directories) {
  const absolute = path.join(root, directory);
  const files = (await readdir(absolute)).filter((name) => name.endsWith('.csv')).sort();
  for (const filename of files) {
    const name = path.basename(filename, '.csv');
    const known = benchmark[name];
    catalog[name] = {
      csv: await readFile(path.join(absolute, filename), 'utf8'),
      metadata: {
        jobs: known ? known[0] : null,
        bestKnown: known ? known[1] : null,
        dataset: directory === 'masclib' ? 'MaScLib' : 'Bundled workload',
        family: name.startsWith('GPU_')
          ? 'gpu'
          : name.startsWith('STC_')
            ? 'setup'
            : 'standard',
      },
    };
  }
}

const wasm = await readFile(wasmPath);
const packed = gzipSync(Buffer.from(JSON.stringify(catalog)), { level: 9, mtime: 0 });
const source = [
  '/* Generated by google-sheets/scripts/build-payload.mjs. */',
  'var IG_PAYLOAD = Object.freeze({',
  `  wasmBase64: ${JSON.stringify(wasm.toString('base64'))},`,
  `  catalogGzipBase64: ${JSON.stringify(packed.toString('base64'))},`,
  `  wasmBytes: ${wasm.length},`,
  `  catalogEntries: ${Object.keys(catalog).length}`,
  '});',
  '',
].join('\n');

await mkdir(path.dirname(output), { recursive: true });
await writeFile(output, source);
console.log(JSON.stringify({
  output,
  wasmBytes: wasm.length,
  catalogEntries: Object.keys(catalog).length,
  catalogGzipBytes: packed.length,
  sourceBytes: Buffer.byteLength(source),
}));
